#!/usr/bin/env bash
set -euo pipefail

plugin_dir="$(cd "$(dirname "$0")/.." && pwd)"

node --check "$plugin_dir/desktop/js/scenarioform.js"

grep -q "Nettoyage réponse incomplète impossible" "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q "var scenarioformDraggedForm = null;" "$plugin_dir/desktop/js/scenarioform.js"
grep -q "var scenarioformDraggedScenario = null;" "$plugin_dir/desktop/js/scenarioform.js"
grep -Fq "\$(document).off('.scenarioform');" "$plugin_dir/desktop/js/scenarioform.js"
! grep -Eq "\\$\\(document\\)\\.on\\(['\"](click|change|keydown|dragstart|dragover|drop|dragend)['\"]" "$plugin_dir/desktop/js/scenarioform.js"

grep -q 'scenarioform_response_value.*ADD COLUMN IF NOT EXISTS.*updated' "$plugin_dir/plugin_info/install.php"
grep -q '`updated` DATETIME NULL' "$plugin_dir/core/config/install.sql"
grep -q "typeof jeedomUtils.hideAlert === 'function'" "$plugin_dir/desktop/js/scenarioform.js"
node "$plugin_dir/tests/validation_regression.js"
test -f "$plugin_dir/desktop/css/scenarioform.css"
test -f "$plugin_dir/EXEMPLE_PRET_A_EMPLOI.md"
test -f "$plugin_dir/ACCES_UTILISATEUR.md"
test -f "$plugin_dir/SECURITE_ET_ACCES.md"
test -f "$plugin_dir/docs/fr_FR/index.md"
test -f "$plugin_dir/desktop/php/documentation.php"
grep -q '"documentation": "index.php?v=d&m=scenarioform&p=documentation"' "$plugin_dir/plugin_info/info.json"
grep -q 'ScenarioForm — Guide d.utilisation' "$plugin_dir/desktop/php/documentation.php"
grep -q "if (!isConnect())" "$plugin_dir/desktop/php/documentation.php"
grep -q '## Créer rapidement un premier exemple' "$plugin_dir/docs/fr_FR/index.md"
grep -q '## Utiliser un formulaire au quotidien' "$plugin_dir/docs/fr_FR/index.md"
grep -q '## Périmètre de la version 2.2' "$plugin_dir/docs/fr_FR/index.md"
grep -q 'future version 2.3' "$plugin_dir/docs/fr_FR/index.md"
grep -q '"display": "scenarioform"' "$plugin_dir/plugin_info/info.json"
grep -q 'Créer le scénario modèle' "$plugin_dir/EXEMPLE_PRET_A_EMPLOI.md"
grep -q 'scenarioform::sendResult()' "$plugin_dir/EXEMPLE_PRET_A_EMPLOI.md"
grep -q 'DÉBUT — TRAITEMENT À PERSONNALISER' "$plugin_dir/EXEMPLE_PRET_A_EMPLOI.md"
grep -q 'Aucun retour reçu' "$plugin_dir/EXEMPLE_PRET_A_EMPLOI.md"
grep -q '## Essayer avec un utilisateur limité' "$plugin_dir/EXEMPLE_PRET_A_EMPLOI.md"
grep -q '## Contrôle final' "$plugin_dir/EXEMPLE_PRET_A_EMPLOI.md"
grep -q 'Ne pas confondre avec l.*onglet.*Équipements' "$plugin_dir/EXEMPLE_PRET_A_EMPLOI.md"
grep -q 'expectResult' "$plugin_dir/core/class/scenarioformFormScenario.class.php"
grep -q 'Attendre un retour métier' "$plugin_dir/desktop/js/scenarioform.js"
grep -q "not_expected: 'Scénario lancé — aucun retour attendu'" "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'ADD COLUMN IF NOT EXISTS `expectResult`' "$plugin_dir/plugin_info/install.php"
grep -q 'scenarioformAdminActions' "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q 'function scenarioformScenarioCanExecute' "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q "hasRight('x', \$currentUser)" "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q 'user::byId' "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q "'scenario' . intval(\$scenario->getId())" "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q "strpos(\$storedRights, 'x')" "$plugin_dir/core/ajax/scenarioform.ajax.php"
! grep -q 'function scenarioformScenarioRightDiagnostic' "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q 'scenarioformCanReadResponseConfiguration' "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q 'scenarioform-user-mode' "$plugin_dir/desktop/php/scenarioform.php"
grep -q 'id="bt_scenarioformAssistant"' "$plugin_dir/desktop/php/scenarioform.php"
grep -q 'function scenarioformOpenGuidedAssistant' "$plugin_dir/desktop/js/scenarioform.js"
grep -q "action: 'createGuidedExample'" "$plugin_dir/desktop/js/scenarioform.js"
grep -q "case 'createGuidedExample':" "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q 'buildGuidedExampleCode' "$plugin_dir/core/class/scenarioform.class.php"
grep -q "'createGuidedExample'" "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q '### Variante rapide avec l.assistant' "$plugin_dir/EXEMPLE_PRET_A_EMPLOI.md"
grep -q "include_file('desktop', 'scenarioform', 'css', 'scenarioform')" "$plugin_dir/desktop/php/scenarioform.php"

test -f "$plugin_dir/core/class/scenarioformFormScenario.class.php"
test -f "$plugin_dir/plugin_info/install.php"

grep -q 'scenarioform_form_scenario' "$plugin_dir/plugin_info/install.php"
grep -q 'UNIQUE KEY `uniq_form_scenario`' "$plugin_dir/plugin_info/install.php"
grep -q 'function scenarioform_ensure_foreign_key' "$plugin_dir/plugin_info/install.php"
grep -q "'fk_scenarioform_field_form'" "$plugin_dir/plugin_info/install.php"
grep -q "'fk_scenarioform_response_form'" "$plugin_dir/plugin_info/install.php"
grep -q "'fk_scenarioform_response_value_field'" "$plugin_dir/plugin_info/install.php"
grep -q "'fk_scenarioform_response_value_response'" "$plugin_dir/plugin_info/install.php"
grep -q 'function syncScenarios' "$plugin_dir/core/class/scenarioformForm.class.php"
grep -q '$scenarios = $form->getScenarios()' "$plugin_dir/core/class/scenarioformResponse.class.php"
grep -q "getRequired()" "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q "prop('required')" "$plugin_dir/desktop/js/scenarioform.js"
grep -q "'requested_scenarios'" "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q "Résultat du lancement" "$plugin_dir/desktop/js/scenarioform.js"
! grep -q "getResponseHistory" "$plugin_dir/core/ajax/scenarioform.ajax.php"
! grep -q "getResponseHistory" "$plugin_dir/desktop/js/scenarioform.js"
! grep -q "getTagsasupprimer" "$plugin_dir/core/class/scenarioformResponse.class.php"
! grep -q "byFormAndName" "$plugin_dir/core/class/scenarioformField.class.php"
! grep -q "loadAvailableScenarios" "$plugin_dir/desktop/js/scenarioform.js"
! grep -q "edit_request_scenario" "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'inputmode="numeric"' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'inférieur ou égal à' "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q 'field-required-min-length-help' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'updateRequiredMinLengthHelp' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'function scenarioformBuildPlaceholder' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'function scenarioformValidateInput' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'scenarioform-field-error' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'if ($required && empty($fieldValue))' "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q 'scenarioformEscapeHtml(scenario.name)' "$plugin_dir/desktop/js/scenarioform.js"
! grep -q 'console.log' "$plugin_dir/desktop/js/scenarioform.js"
! grep -q '🟢\|🔴' "$plugin_dir/desktop/js/scenarioform.js"
grep -q "removeClass('active')" "$plugin_dir/desktop/js/scenarioform.js"
grep -q "loadRequestDetail(requestId, savedFormId)" "$plugin_dir/desktop/js/scenarioform.js"
grep -q "case 'reorderForms'" "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q 'bt_form_up' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'scenarioform-empty-state' "$plugin_dir/desktop/php/scenarioform.php"
grep -q "'Ajouter des champs'" "$plugin_dir/desktop/js/scenarioform.js"
test "$(grep -c 'id="bt_historyForm"' "$plugin_dir/desktop/js/scenarioform.js")" -eq 1
grep -q "showFormValues(formId, true)" "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'function loadFormHistory' "$plugin_dir/desktop/js/scenarioform.js"
grep -q "scenarioformViewMode = 'entry'" "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'scenarioformValuesRequest.abort' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'nextDisplayOrder' "$plugin_dir/core/class/scenarioformField.class.php"
grep -q 'comparisonFieldId' "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q 'data-compare-field-id' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'edit_field_comparison_operator' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'field-comparison-warning' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'compatibleFields.length > 0 || hasConfiguredRule' "$plugin_dir/desktop/js/scenarioform.js"
test -f "$plugin_dir/core/api/scenarioform.php"
grep -q '#scenarioform_callback_token#' "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q 'getInternalCallbackUrl' "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q 'function getInternalCallbackUrl' "$plugin_dir/core/class/scenarioform.class.php"
grep -q 'REQUEST_METHOD' "$plugin_dir/core/api/scenarioform.php"
grep -q 'scenarioformCallbackRate' "$plugin_dir/core/api/scenarioform.php"
grep -q 'Cache-Control: no-store' "$plugin_dir/core/api/scenarioform.php"
grep -q '#scenarioform_scenario_id#' "$plugin_dir/core/class/scenarioformResponse.class.php"
grep -q 'scenario_results' "$plugin_dir/core/api/scenarioform.php"
grep -q 'scenarioformHistoryPollTimer' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'scenarioformResultPollTimer' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'function scenarioformStopResultPolling' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'id="bt_newEntryAfterExecution"' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'id="bt_historyAfterExecution"' "$plugin_dir/desktop/js/scenarioform.js"
grep -q "attr('data-form-name') || ('#' + formId)" "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'scenarioform-card-header-actions' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'let scenarioOpenButtons' "$plugin_dir/desktop/js/scenarioform.js"
grep -q "\$('#bt_editForm, #bt_removeForm').prop('disabled', false)" "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'id="bt_editForm" disabled' "$plugin_dir/desktop/js/scenarioform.js"
grep -q "case 'getScenarioResults'" "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q 'Résultat du traitement' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'bt_createScenarioTemplate' "$plugin_dir/desktop/js/scenarioform.js"
grep -q "case 'createScenarioTemplate'" "$plugin_dir/core/ajax/scenarioform.ajax.php"
sed -n "/case 'createScenarioTemplate':/,/case 'getRequestDetail':/p" "$plugin_dir/core/ajax/scenarioform.ajax.php" | grep -q "include_file('core', 'scenarioformField'"
grep -q 'function buildScenarioTemplateCode' "$plugin_dir/core/class/scenarioform.class.php"
grep -q 'scenarioElement::saveAjaxElement' "$plugin_dir/core/class/scenarioform.class.php"
grep -q 'return is_object($scenario) ? $scenario : null;' "$plugin_dir/core/class/scenarioformFormScenario.class.php"
grep -q 'return is_object($scenario) ? $scenario : null;' "$plugin_dir/core/class/scenarioformRequestScenario.class.php"
! grep -q 'create_form_scenario_template' "$plugin_dir/desktop/js/scenarioform.js"
! grep -q "init('create_scenario_template')" "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q 'form.fields.length > 0' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'form.scenarios.length === 0' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'function showFormHistory' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'bt_backHistoryToEntry' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'function scenarioformReturnToRequestDetail' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'scenarioformReturnToRequestDetail(requestId)' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'scenarioformPendingReuseResponseId' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'function scenarioformRefreshTemplateButton' "$plugin_dir/desktop/js/scenarioform.js"
grep -q "'data-scenario-count'" "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'function isScenarioFormContext' "$plugin_dir/core/class/scenarioform.class.php"
grep -q 'function isActiveScenarioFormTags' "$plugin_dir/core/class/scenarioform.class.php"
grep -q 'scenarioform::isScenarioFormContext($scenario)' "$plugin_dir/core/class/scenarioform.class.php"
grep -q 'DÉBUT — VALEURS REÇUES DE SCENARIOFORM' "$plugin_dir/core/class/scenarioform.class.php"
grep -q 'FIN — VALEURS REÇUES DE SCENARIOFORM' "$plugin_dir/core/class/scenarioform.class.php"
grep -q 'DÉBUT — TRAITEMENT À PERSONNALISER' "$plugin_dir/core/class/scenarioform.class.php"
grep -q 'FIN — TRAITEMENT À PERSONNALISER' "$plugin_dir/core/class/scenarioform.class.php"
grep -q 'DÉBUT — MESSAGE DE RETOUR' "$plugin_dir/core/class/scenarioform.class.php"
grep -q 'FIN — MESSAGE DE RETOUR' "$plugin_dir/core/class/scenarioform.class.php"
! grep -q 'VALEURS PAR DÉFAUT / LANCEMENT MANUEL' "$plugin_dir/core/class/scenarioform.class.php"
grep -q "lancement manuel ignoré par le scénario modèle" "$plugin_dir/core/class/scenarioform.class.php"
python3 - "$plugin_dir" <<'PY'
import pathlib
import sys

source = (pathlib.Path(sys.argv[1]) / 'core/class/scenarioform.class.php').read_text()
values_begin = source.index('DÉBUT — VALEURS REÇUES DE SCENARIOFORM')
values_end = source.index('FIN — VALEURS REÇUES DE SCENARIOFORM')
received = source.index("$lines[] = 'if ($sf_lancement_scenarioform) {';")
business_begin = source.index('DÉBUT — TRAITEMENT À PERSONNALISER', received)
business_end = source.index('FIN — TRAITEMENT À PERSONNALISER', business_begin)
message_begin = source.index('DÉBUT — MESSAGE DE RETOUR', business_end)
message_end = source.index('FIN — MESSAGE DE RETOUR', message_begin)
manual_else = source.index("$lines[] = '} else {';", message_end)
assert received < values_begin < values_end < business_begin < business_end
assert business_end < message_begin < message_end < manual_else
PY
grep -q "'#scenarioform_origin#' => 'scenarioform'" "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q '#scenarioform_launch_nonce#' "$plugin_dir/core/class/scenarioformResponse.class.php"
grep -q 'scenarioformLaunchContext::' "$plugin_dir/core/class/scenarioform.class.php"
grep -q 'validatedLaunchContexts' "$plugin_dir/core/class/scenarioform.class.php"
grep -q 'function sendResult' "$plugin_dir/core/class/scenarioform.class.php"
grep -q 'class scenarioformCmd extends cmd' "$plugin_dir/core/class/scenarioform.class.php"
grep -q 'ensureResultActionEquipment' "$plugin_dir/plugin_info/install.php"
grep -q 'function scenarioform_load_plugin_classes' "$plugin_dir/plugin_info/install.php"
grep -q "require_once \$scenarioformClassDirectory" "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q "'scenarioformRequest'" "$plugin_dir/plugin_info/install.php"
grep -q "setSubType('message')" "$plugin_dir/core/class/scenarioform.class.php"
grep -q 'scenarioExpression::tag' "$plugin_dir/core/class/scenarioform.class.php"
grep -q 'target_scenario_id' "$plugin_dir/core/class/scenarioform.class.php"
grep -q 'recordLatestPendingScenarioResult' "$plugin_dir/core/class/scenarioformResponse.class.php"
! grep -q 'INSERT IGNORE INTO `scenarioform_form_scenario`' "$plugin_dir/plugin_info/install.php"
grep -q 'SELECT DISTINCT scenario_id' "$plugin_dir/core/class/scenarioform.class.php"
grep -q 'setIsEnable(0)' "$plugin_dir/core/class/scenarioform.class.php"
grep -q 'expirePendingScenarioResults' "$plugin_dir/core/class/scenarioformResponse.class.php"
grep -q "scenario_result_timeout" "$plugin_dir/plugin_info/configuration.php"
grep -q 'Valeur par défaut : 120 secondes' "$plugin_dir/plugin_info/configuration.php"
test "$(grep -c "config::byKey('scenario_result_timeout', 'scenarioform', 120)" "$plugin_dir/core/ajax/scenarioform.ajax.php")" -eq 3
! grep -q "config::byKey('scenario_result_timeout', 'scenarioform', 900)" "$plugin_dir/core/ajax/scenarioform.ajax.php"
grep -q "\$result\['status'\] = 'timeout'" "$plugin_dir/core/class/scenarioformResponse.class.php"
grep -q "timeout: 'Aucun retour reçu — consultez le journal Jeedom du scénario'" "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'Ses formulaires, champs, associations aux scénarios, réponses et valeurs seront également supprimés' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'Les scénarios Jeedom eux-mêmes seront conservés' "$plugin_dir/desktop/js/scenarioform.js"
! grep -Fq "'token'     =>" "$plugin_dir/core/ajax/scenarioform.ajax.php"
! grep -q "' token='" "$plugin_dir/core/class/scenarioformResponse.class.php"
! grep -q "' configuration='" "$plugin_dir/core/class/scenarioformResponse.class.php"
! grep -q 'print_r(\$link' "$plugin_dir/core/class/scenarioformRequest.class.php"
grep -q 'min-height: 44px' "$plugin_dir/desktop/css/scenarioform.css"
grep -q 'font-size: 16px' "$plugin_dir/desktop/css/scenarioform.css"
grep -q 'overflow-wrap: anywhere' "$plugin_dir/desktop/css/scenarioform.css"
grep -q 'id="bt_toggleMobileManagement"' "$plugin_dir/desktop/php/scenarioform.php"
grep -q 'scenarioform-mobile-management-open' "$plugin_dir/desktop/js/scenarioform.js"
grep -q 'scenarioform-mobile-admin-action' "$plugin_dir/desktop/css/scenarioform.css"
! grep -q 'GET VALUES - NOMBRE=' "$plugin_dir/core/class/scenarioformResponse.class.php"
! find "$plugin_dir" -type f -name '*1608*' | grep -q .

if command -v php >/dev/null 2>&1; then
    while IFS= read -r -d '' file; do
        php -l "$file" >/dev/null
    done < <(find "$plugin_dir" -name '*.php' -print0)
else
    echo "PHP absent : lint PHP à exécuter sur la VM Jeedom."
fi

echo "Contrôles statiques ScenarioForm V2 : OK"
